### ISSUE TITLE
Null Pointer on latest 1.19 Paper Build + Latest Plugin Build

### ISSUE THREAD

**Issue by Hexical1** [IntellectualSites/Plot2Dynmap#110]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

There is a null pointer exception error when loading the latest Plot2Dynmap.jar on 1.19, which from what I can tell is not allowing the plugin to register all new plots correctly.

### To Reproduce

1.) Load Plot2Dynmap on 1.19 Paper Server
2.) Watch console for error

### Expected behaviour

1.) Load Plot2Dynmap on 1.19 Paper Server
2.) It loads with no errors

### Error log (if applicable)

https://paste.gg/p/anonymous/685505f896bb4b0c86b3e5adefea7c6e

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/66e38163c44240c281dd4e7544140c36

### Plot2Dynmap Version

Plot2Dynmap 6.0.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/1292/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm not able to replicate the issue using the latest version of PaperMC, Plot2Dymap and PlotSquared.
