### ISSUE TITLE
Plot2Dynmap does not work with Paper 1.14.4

### ISSUE THREAD

**Issue by aurel85** [IntellectualSites/plot2dynmap#2]
Hi,

Plot2Dynmap does not work with Paper 1.14.4 :  

https://pastebin.com/SARv6RDd

This error comes back every 5min.

I use PaperSpigot 1.14.4 (version 230), PlotSquared 4.409, Dynmap 3.0 beta 5 and the new version of Plot2Dynmap for 1.13 & 1.14.

**Comment by NotMyFault** [comment]
If the issue is still relevant on 1.16.5 and PlotSquared v5, please raise a new issue and fill out the template.

**Comment by aurel85** [comment]
Everything is ok with PlotSquared V5, Plot2Dynmap (last version) and Paper 1.16.5 !
